### ISSUE TITLE
Error while checking connectivity against bucket from another account 

### ISSUE THREAD

**Issue by algra** [indix/gocd-s3-artifacts#44] opened 2016-11-24 21:18 UTC
Hi guys,

We have GoCD running in one account, and artefacts bucket in another one, but GoCD still can access it because AWS policies are allowing it.

The problem with the s3material plugin is that during connectivity check it executes `client.listBuckets()`:

https://github.com/indix/gocd-s3-artifacts/blob/master/utils/src/main/java/com/indix/gocd/utils/store/S3ArtifactStore.java#L100-L106

which returns list of buckets only from the same account, which obviously lead to failed check because bucket is never included in the returned list.

Would it make sense to fix it with, like, `client.listObjects(...)`, with some random prefix, which will lead to empty result list if the bucket exists and to exception if it doesn't or GoCD has no permissions to list bucket it, which will be required later during polling anyway?

If you're ok with the proposed solution, either me or my colleagues will send a PR. What do you think?

**Comment by ashwanthkumar** [comment] 2016-11-25 02:29
@algra Sorry you're running into the problem - I think this is a duplicate of #12 
To me both `client.listObjects(...)` and `client.doesBucketExist` sounds good. 

@haimizrael @manojlds @brewkode what do you guys think?

**Comment by ajitchahal** [comment] 2016-11-28 10:44
Any news on this..? I would really appreciate this fix.

**Comment by ashwanthkumar** [comment] 2016-11-28 12:06
@ajitchahal Would you be able to take a stab at sending the above fix as a PR? The approaches to solving the problem has been laid out in this issue and on #12

**Comment by manojlds** [comment] 2017-09-07 12:00
This is taken care of in v5.0.1

**Closed by manojlds** 2017-09-07 12:00 UTC
